### ISSUE TITLE
user_defined_variables.xml and file_upload_template.xml templates not found.

### ISSUE THREAD

**Issue by dashawn888** [lanitgithub/jmeter_api#9]
```
from jmeter_api.basics.sampler.elements import UserDefinedVariables
from jmeter_api.samplers.http_request.elements import HttpRequest
from jmeter_api.non_test_elements.test_plan.elements import TestPlan
from jmeter_api.thread_groups.common_thread_group.elements import CommonThreadGroup

req = HttpRequest()
req.add_user_variable(UserDefinedVariables())
TestPlan().append(CommonThreadGroup().append(req)).to_xml()
```
Gives
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    TestPlan().append(CommonThreadGroup().append(req)).to_xml()
  File "site-packages/jmeter_api/non_test_elements/test_plan/elements.py", line 128, in to_xml
    content_root.text = self._render_inner_elements()
  File "site-packages/jmeter_api/basics/utils.py", line 61, in _render_inner_elements
    xml_data += element.to_xml()
  File "site-packages/jmeter_api/thread_groups/common_thread_group/elements.py", line 79, in to_xml
    content_root.text = self._render_inner_elements()
  File "site-packages/jmeter_api/basics/utils.py", line 61, in _render_inner_elements
    xml_data += element.to_xml()
  File "site-packages/jmeter_api/samplers/http_request/elements.py", line 593, in to_xml
    content_root.text = self._render_user_variables()
  File "site-packages/jmeter_api/samplers/http_request/elements.py", line 437, in _render_user_variables
    xml_str += element.to_xml()
  File "site-packages/jmeter_api/basics/sampler/elements.py", line 161, in to_xml
    xml_tree = self.get_template()
  File "site-packages/jmeter_api/basics/utils.py", line 20, in get_template
    with open(template_path) as file:
FileNotFoundError: [Errno 2] No such file or directory: 'site-packages/jmeter_api/basics/sampler/user_defined_variables.xml'
```

Am I using it correctly?

Thanks,

Shawn

**Comment by dashawn888** [comment]
I got mine working by creating the user_defined_variables.xml file with this content.

```
<elementProp name="searchTxt" elementType="HTTPArgument">
    <boolProp name="HTTPArgument.always_encode"></boolProp>
    <stringProp name="Argument.value"></stringProp>
    <stringProp name="Argument.metadata"></stringProp>
    <boolProp name="HTTPArgument.use_equals"></boolProp>
    <stringProp name="Argument.name"></stringProp>
</elementProp>
```
